libname mylib 'C:\Users\wojte\Documents\Inzynierka\kod\extdemo';
filename src_cat catalog 'mylib.em61ext.reg.source';
filename mydata 'C:\Users\wojte\Documents\Inzynierka\kod\extdemo\main.sas';
data _null_;
	file src_cat;
	infile mydata;
	input;
	put _infile_;
run;
filename src_cat catalog 'mylib.em61ext.reg_create.source';
filename mydata 'C:\Users\wojte\Documents\Inzynierka\kod\extdemo\create.sas';
data _null_;
	file src_cat;
	infile mydata;
	input;
	put _infile_;
run;
filename src_cat catalog 'mylib.em61ext.reg_train.source';
filename mydata 'C:\Users\wojte\Documents\Inzynierka\kod\extdemo\train.sas';
data _null_;
	file src_cat;
	infile mydata;
	input;
	put _infile_;
run;
filename src_cat catalog 'mylib.em61ext.reg_score.source';
filename mydata 'C:\Users\wojte\Documents\Inzynierka\kod\extdemo\score.sas';
data _null_;
	file src_cat;
	infile mydata;
	input;
	put _infile_;
run;

proc catalog cat=mylib.em61text;
	copy out=sashelp.em61text3;
run;
